// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/user/cat/v1/cat.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BaseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseRequestMultiError, or
// nil if none found.
func (m *BaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BaseRequestMultiError(errors)
	}

	return nil
}

// BaseRequestMultiError is an error wrapping multiple validation errors
// returned by BaseRequest.ValidateAll() if the designated constraints aren't met.
type BaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseRequestMultiError) AllErrors() []error { return m }

// BaseRequestValidationError is the validation error returned by
// BaseRequest.Validate if the designated constraints aren't met.
type BaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseRequestValidationError) ErrorName() string { return "BaseRequestValidationError" }

// Error satisfies the builtin error interface
func (e BaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseRequestValidationError{}

// Validate checks the field values on BaseResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseResponseMultiError, or
// nil if none found.
func (m *BaseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BaseResponseMultiError(errors)
	}

	return nil
}

// BaseResponseMultiError is an error wrapping multiple validation errors
// returned by BaseResponse.ValidateAll() if the designated constraints aren't met.
type BaseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseResponseMultiError) AllErrors() []error { return m }

// BaseResponseValidationError is the validation error returned by
// BaseResponse.Validate if the designated constraints aren't met.
type BaseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseResponseValidationError) ErrorName() string { return "BaseResponseValidationError" }

// Error satisfies the builtin error interface
func (e BaseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseResponseValidationError{}

// Validate checks the field values on GetUserCatListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatListRequestMultiError, or nil if none found.
func (m *GetUserCatListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() < 1 {
		err := GetUserCatListRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetSize(); val < 10 || val > 200 {
		err := GetUserCatListRequestValidationError{
			field:  "Size",
			reason: "value must be inside range [10, 200]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetCType(); val < 0 || val > 20 {
		err := GetUserCatListRequestValidationError{
			field:  "CType",
			reason: "value must be inside range [0, 20]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserCatListRequestMultiError(errors)
	}

	return nil
}

// GetUserCatListRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserCatListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserCatListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatListRequestMultiError) AllErrors() []error { return m }

// GetUserCatListRequestValidationError is the validation error returned by
// GetUserCatListRequest.Validate if the designated constraints aren't met.
type GetUserCatListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatListRequestValidationError) ErrorName() string {
	return "GetUserCatListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCatListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatListRequestValidationError{}

// Validate checks the field values on UserCatListItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserCatListItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserCatListItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserCatListItemMultiError, or nil if none found.
func (m *UserCatListItem) ValidateAll() error {
	return m.validate(true)
}

func (m *UserCatListItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Gender

	// no validation rules for BreedType

	// no validation rules for Weight

	// no validation rules for Birthday

	// no validation rules for NeuterStatus

	// no validation rules for HealthStatus

	// no validation rules for DewormedStatus

	// no validation rules for VaccineStatus

	// no validation rules for Remark

	if len(errors) > 0 {
		return UserCatListItemMultiError(errors)
	}

	return nil
}

// UserCatListItemMultiError is an error wrapping multiple validation errors
// returned by UserCatListItem.ValidateAll() if the designated constraints
// aren't met.
type UserCatListItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserCatListItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserCatListItemMultiError) AllErrors() []error { return m }

// UserCatListItemValidationError is the validation error returned by
// UserCatListItem.Validate if the designated constraints aren't met.
type UserCatListItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCatListItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCatListItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCatListItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCatListItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCatListItemValidationError) ErrorName() string { return "UserCatListItemValidationError" }

// Error satisfies the builtin error interface
func (e UserCatListItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCatListItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCatListItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCatListItemValidationError{}

// Validate checks the field values on UserCatList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserCatList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserCatList with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserCatListMultiError, or
// nil if none found.
func (m *UserCatList) ValidateAll() error {
	return m.validate(true)
}

func (m *UserCatList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserCatListValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserCatListValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserCatListValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return UserCatListMultiError(errors)
	}

	return nil
}

// UserCatListMultiError is an error wrapping multiple validation errors
// returned by UserCatList.ValidateAll() if the designated constraints aren't met.
type UserCatListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserCatListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserCatListMultiError) AllErrors() []error { return m }

// UserCatListValidationError is the validation error returned by
// UserCatList.Validate if the designated constraints aren't met.
type UserCatListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCatListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCatListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCatListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCatListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCatListValidationError) ErrorName() string { return "UserCatListValidationError" }

// Error satisfies the builtin error interface
func (e UserCatListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCatList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCatListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCatListValidationError{}

// Validate checks the field values on GetUserCatListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatListReplyMultiError, or nil if none found.
func (m *GetUserCatListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserCatListReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserCatListReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserCatListReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserCatListReplyMultiError(errors)
	}

	return nil
}

// GetUserCatListReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserCatListReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserCatListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatListReplyMultiError) AllErrors() []error { return m }

// GetUserCatListReplyValidationError is the validation error returned by
// GetUserCatListReply.Validate if the designated constraints aren't met.
type GetUserCatListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatListReplyValidationError) ErrorName() string {
	return "GetUserCatListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCatListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatListReplyValidationError{}

// Validate checks the field values on CreateUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserCatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserCatRequestMultiError, or nil if none found.
func (m *CreateUserCatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserCatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := CreateUserCatRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetGender(); val < 0 || val > 2 {
		err := CreateUserCatRequestValidationError{
			field:  "Gender",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetBreedType(); val < 0 || val > 30 {
		err := CreateUserCatRequestValidationError{
			field:  "BreedType",
			reason: "value must be inside range [0, 30]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetWeight(); val < 0 || val > 50 {
		err := CreateUserCatRequestValidationError{
			field:  "Weight",
			reason: "value must be inside range [0, 50]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBirthday()) < 1 {
		err := CreateUserCatRequestValidationError{
			field:  "Birthday",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetNeuterStatus(); val < 0 || val > 2 {
		err := CreateUserCatRequestValidationError{
			field:  "NeuterStatus",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetHealthStatus(); val < 0 || val > 4 {
		err := CreateUserCatRequestValidationError{
			field:  "HealthStatus",
			reason: "value must be inside range [0, 4]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for HealthDesc

	if val := m.GetDewormedStatus(); val < 0 || val > 2 {
		err := CreateUserCatRequestValidationError{
			field:  "DewormedStatus",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetVaccineStatus(); val < 0 || val > 3 {
		err := CreateUserCatRequestValidationError{
			field:  "VaccineStatus",
			reason: "value must be inside range [0, 3]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for VaccineLastDate

	// no validation rules for VaccineCertImage

	if l := utf8.RuneCountInString(m.GetRemark()); l < 1 || l > 500 {
		err := CreateUserCatRequestValidationError{
			field:  "Remark",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateUserCatRequestMultiError(errors)
	}

	return nil
}

// CreateUserCatRequestMultiError is an error wrapping multiple validation
// errors returned by CreateUserCatRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateUserCatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserCatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserCatRequestMultiError) AllErrors() []error { return m }

// CreateUserCatRequestValidationError is the validation error returned by
// CreateUserCatRequest.Validate if the designated constraints aren't met.
type CreateUserCatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserCatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserCatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserCatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserCatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserCatRequestValidationError) ErrorName() string {
	return "CreateUserCatRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserCatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserCatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserCatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserCatRequestValidationError{}

// Validate checks the field values on CreateUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserCatReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserCatReplyMultiError, or nil if none found.
func (m *CreateUserCatReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserCatReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return CreateUserCatReplyMultiError(errors)
	}

	return nil
}

// CreateUserCatReplyMultiError is an error wrapping multiple validation errors
// returned by CreateUserCatReply.ValidateAll() if the designated constraints
// aren't met.
type CreateUserCatReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserCatReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserCatReplyMultiError) AllErrors() []error { return m }

// CreateUserCatReplyValidationError is the validation error returned by
// CreateUserCatReply.Validate if the designated constraints aren't met.
type CreateUserCatReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserCatReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserCatReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserCatReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserCatReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserCatReplyValidationError) ErrorName() string {
	return "CreateUserCatReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserCatReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserCatReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserCatReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserCatReplyValidationError{}

// Validate checks the field values on UpdateUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserCatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserCatRequestMultiError, or nil if none found.
func (m *UpdateUserCatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserCatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateUserCatRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := UpdateUserCatRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetGender(); val < 0 || val > 2 {
		err := UpdateUserCatRequestValidationError{
			field:  "Gender",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetBreedType(); val < 0 || val > 30 {
		err := UpdateUserCatRequestValidationError{
			field:  "BreedType",
			reason: "value must be inside range [0, 30]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetWeight(); val < 0 || val > 50 {
		err := UpdateUserCatRequestValidationError{
			field:  "Weight",
			reason: "value must be inside range [0, 50]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBirthday()) < 1 {
		err := UpdateUserCatRequestValidationError{
			field:  "Birthday",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetNeuterStatus(); val < 0 || val > 2 {
		err := UpdateUserCatRequestValidationError{
			field:  "NeuterStatus",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetHealthStatus(); val < 0 || val > 4 {
		err := UpdateUserCatRequestValidationError{
			field:  "HealthStatus",
			reason: "value must be inside range [0, 4]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for HealthDesc

	if val := m.GetDewormedStatus(); val < 0 || val > 2 {
		err := UpdateUserCatRequestValidationError{
			field:  "DewormedStatus",
			reason: "value must be inside range [0, 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetVaccineStatus(); val < 0 || val > 3 {
		err := UpdateUserCatRequestValidationError{
			field:  "VaccineStatus",
			reason: "value must be inside range [0, 3]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for VaccineLastDate

	// no validation rules for VaccineCertImage

	if l := utf8.RuneCountInString(m.GetRemark()); l < 1 || l > 500 {
		err := UpdateUserCatRequestValidationError{
			field:  "Remark",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateUserCatRequestMultiError(errors)
	}

	return nil
}

// UpdateUserCatRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateUserCatRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateUserCatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserCatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserCatRequestMultiError) AllErrors() []error { return m }

// UpdateUserCatRequestValidationError is the validation error returned by
// UpdateUserCatRequest.Validate if the designated constraints aren't met.
type UpdateUserCatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserCatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserCatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserCatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserCatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserCatRequestValidationError) ErrorName() string {
	return "UpdateUserCatRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserCatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserCatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserCatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserCatRequestValidationError{}

// Validate checks the field values on UpdateUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserCatReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserCatReplyMultiError, or nil if none found.
func (m *UpdateUserCatReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserCatReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return UpdateUserCatReplyMultiError(errors)
	}

	return nil
}

// UpdateUserCatReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateUserCatReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateUserCatReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserCatReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserCatReplyMultiError) AllErrors() []error { return m }

// UpdateUserCatReplyValidationError is the validation error returned by
// UpdateUserCatReply.Validate if the designated constraints aren't met.
type UpdateUserCatReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserCatReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserCatReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserCatReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserCatReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserCatReplyValidationError) ErrorName() string {
	return "UpdateUserCatReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserCatReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserCatReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserCatReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserCatReplyValidationError{}

// Validate checks the field values on DeleteUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserCatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserCatRequestMultiError, or nil if none found.
func (m *DeleteUserCatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserCatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteUserCatRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteUserCatRequestMultiError(errors)
	}

	return nil
}

// DeleteUserCatRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteUserCatRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteUserCatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserCatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserCatRequestMultiError) AllErrors() []error { return m }

// DeleteUserCatRequestValidationError is the validation error returned by
// DeleteUserCatRequest.Validate if the designated constraints aren't met.
type DeleteUserCatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserCatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserCatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserCatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserCatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserCatRequestValidationError) ErrorName() string {
	return "DeleteUserCatRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserCatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteUserCatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteUserCatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserCatRequestValidationError{}

// Validate checks the field values on DeleteUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserCatReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserCatReplyMultiError, or nil if none found.
func (m *DeleteUserCatReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserCatReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return DeleteUserCatReplyMultiError(errors)
	}

	return nil
}

// DeleteUserCatReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteUserCatReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteUserCatReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserCatReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserCatReplyMultiError) AllErrors() []error { return m }

// DeleteUserCatReplyValidationError is the validation error returned by
// DeleteUserCatReply.Validate if the designated constraints aren't met.
type DeleteUserCatReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserCatReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserCatReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserCatReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserCatReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserCatReplyValidationError) ErrorName() string {
	return "DeleteUserCatReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserCatReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteUserCatReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteUserCatReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserCatReplyValidationError{}

// Validate checks the field values on GetUserCatRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatRequestMultiError, or nil if none found.
func (m *GetUserCatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetUserCatRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserCatRequestMultiError(errors)
	}

	return nil
}

// GetUserCatRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserCatRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserCatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatRequestMultiError) AllErrors() []error { return m }

// GetUserCatRequestValidationError is the validation error returned by
// GetUserCatRequest.Validate if the designated constraints aren't met.
type GetUserCatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatRequestValidationError) ErrorName() string {
	return "GetUserCatRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatRequestValidationError{}

// Validate checks the field values on UserCatInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserCatInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserCatInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserCatInfoMultiError, or
// nil if none found.
func (m *UserCatInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserCatInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Gender

	// no validation rules for CatType

	// no validation rules for BreedType

	// no validation rules for Weight

	// no validation rules for Birthday

	// no validation rules for NeuterStatus

	// no validation rules for HealthStatus

	// no validation rules for HealthDesc

	// no validation rules for DewormedStatus

	// no validation rules for VaccineStatus

	// no validation rules for VaccineLastDate

	// no validation rules for VaccineCertImage

	// no validation rules for Remark

	if len(errors) > 0 {
		return UserCatInfoMultiError(errors)
	}

	return nil
}

// UserCatInfoMultiError is an error wrapping multiple validation errors
// returned by UserCatInfo.ValidateAll() if the designated constraints aren't met.
type UserCatInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserCatInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserCatInfoMultiError) AllErrors() []error { return m }

// UserCatInfoValidationError is the validation error returned by
// UserCatInfo.Validate if the designated constraints aren't met.
type UserCatInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCatInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCatInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCatInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCatInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCatInfoValidationError) ErrorName() string { return "UserCatInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserCatInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCatInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCatInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCatInfoValidationError{}

// Validate checks the field values on GetUserCatReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatReplyMultiError, or nil if none found.
func (m *GetUserCatReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserCatReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserCatReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserCatReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserCatReplyMultiError(errors)
	}

	return nil
}

// GetUserCatReplyMultiError is an error wrapping multiple validation errors
// returned by GetUserCatReply.ValidateAll() if the designated constraints
// aren't met.
type GetUserCatReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatReplyMultiError) AllErrors() []error { return m }

// GetUserCatReplyValidationError is the validation error returned by
// GetUserCatReply.Validate if the designated constraints aren't met.
type GetUserCatReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatReplyValidationError) ErrorName() string { return "GetUserCatReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetUserCatReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatReplyValidationError{}

// Validate checks the field values on GetUserCatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatsRequestMultiError, or nil if none found.
func (m *GetUserCatsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserCatsRequestMultiError(errors)
	}

	return nil
}

// GetUserCatsRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserCatsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserCatsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatsRequestMultiError) AllErrors() []error { return m }

// GetUserCatsRequestValidationError is the validation error returned by
// GetUserCatsRequest.Validate if the designated constraints aren't met.
type GetUserCatsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatsRequestValidationError) ErrorName() string {
	return "GetUserCatsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCatsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatsRequestValidationError{}

// Validate checks the field values on CatItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CatItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CatItem with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CatItemMultiError, or nil if none found.
func (m *CatItem) ValidateAll() error {
	return m.validate(true)
}

func (m *CatItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Gender

	// no validation rules for CatType

	// no validation rules for BreedType

	if len(errors) > 0 {
		return CatItemMultiError(errors)
	}

	return nil
}

// CatItemMultiError is an error wrapping multiple validation errors returned
// by CatItem.ValidateAll() if the designated constraints aren't met.
type CatItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CatItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CatItemMultiError) AllErrors() []error { return m }

// CatItemValidationError is the validation error returned by CatItem.Validate
// if the designated constraints aren't met.
type CatItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CatItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CatItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CatItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CatItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CatItemValidationError) ErrorName() string { return "CatItemValidationError" }

// Error satisfies the builtin error interface
func (e CatItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCatItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CatItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CatItemValidationError{}

// Validate checks the field values on GetUserCatsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserCatsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCatsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCatsReplyMultiError, or nil if none found.
func (m *GetUserCatsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCatsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserCatsReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserCatsReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserCatsReplyValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserCatsReplyMultiError(errors)
	}

	return nil
}

// GetUserCatsReplyMultiError is an error wrapping multiple validation errors
// returned by GetUserCatsReply.ValidateAll() if the designated constraints
// aren't met.
type GetUserCatsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCatsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCatsReplyMultiError) AllErrors() []error { return m }

// GetUserCatsReplyValidationError is the validation error returned by
// GetUserCatsReply.Validate if the designated constraints aren't met.
type GetUserCatsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCatsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCatsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCatsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCatsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCatsReplyValidationError) ErrorName() string { return "GetUserCatsReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetUserCatsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCatsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCatsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCatsReplyValidationError{}
