// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/user/v1/user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BaseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseRequestMultiError, or
// nil if none found.
func (m *BaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BaseRequestMultiError(errors)
	}

	return nil
}

// BaseRequestMultiError is an error wrapping multiple validation errors
// returned by BaseRequest.ValidateAll() if the designated constraints aren't met.
type BaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseRequestMultiError) AllErrors() []error { return m }

// BaseRequestValidationError is the validation error returned by
// BaseRequest.Validate if the designated constraints aren't met.
type BaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseRequestValidationError) ErrorName() string { return "BaseRequestValidationError" }

// Error satisfies the builtin error interface
func (e BaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseRequestValidationError{}

// Validate checks the field values on BaseResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseResponseMultiError, or
// nil if none found.
func (m *BaseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BaseResponseMultiError(errors)
	}

	return nil
}

// BaseResponseMultiError is an error wrapping multiple validation errors
// returned by BaseResponse.ValidateAll() if the designated constraints aren't met.
type BaseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseResponseMultiError) AllErrors() []error { return m }

// BaseResponseValidationError is the validation error returned by
// BaseResponse.Validate if the designated constraints aren't met.
type BaseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseResponseValidationError) ErrorName() string { return "BaseResponseValidationError" }

// Error satisfies the builtin error interface
func (e BaseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseResponseValidationError{}

// Validate checks the field values on WebLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WebLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebLoginRequestMultiError, or nil if none found.
func (m *WebLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LoginType

	if l := utf8.RuneCountInString(m.GetLoginIdentity()); l < 1 || l > 191 {
		err := WebLoginRequestValidationError{
			field:  "LoginIdentity",
			reason: "value length must be between 1 and 191 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Password

	// no validation rules for VerifyCode

	// no validation rules for AuthCode

	if len(errors) > 0 {
		return WebLoginRequestMultiError(errors)
	}

	return nil
}

// WebLoginRequestMultiError is an error wrapping multiple validation errors
// returned by WebLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type WebLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLoginRequestMultiError) AllErrors() []error { return m }

// WebLoginRequestValidationError is the validation error returned by
// WebLoginRequest.Validate if the designated constraints aren't met.
type WebLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLoginRequestValidationError) ErrorName() string { return "WebLoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e WebLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLoginRequestValidationError{}

// Validate checks the field values on WebLoginInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebLoginInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLoginInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebLoginInfoMultiError, or
// nil if none found.
func (m *WebLoginInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLoginInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for LoginValidPeriod

	if len(errors) > 0 {
		return WebLoginInfoMultiError(errors)
	}

	return nil
}

// WebLoginInfoMultiError is an error wrapping multiple validation errors
// returned by WebLoginInfo.ValidateAll() if the designated constraints aren't met.
type WebLoginInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLoginInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLoginInfoMultiError) AllErrors() []error { return m }

// WebLoginInfoValidationError is the validation error returned by
// WebLoginInfo.Validate if the designated constraints aren't met.
type WebLoginInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLoginInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLoginInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLoginInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLoginInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLoginInfoValidationError) ErrorName() string { return "WebLoginInfoValidationError" }

// Error satisfies the builtin error interface
func (e WebLoginInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLoginInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLoginInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLoginInfoValidationError{}

// Validate checks the field values on WebLoginReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebLoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLoginReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebLoginReplyMultiError, or
// nil if none found.
func (m *WebLoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WebLoginReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WebLoginReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WebLoginReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WebLoginReplyMultiError(errors)
	}

	return nil
}

// WebLoginReplyMultiError is an error wrapping multiple validation errors
// returned by WebLoginReply.ValidateAll() if the designated constraints
// aren't met.
type WebLoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLoginReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLoginReplyMultiError) AllErrors() []error { return m }

// WebLoginReplyValidationError is the validation error returned by
// WebLoginReply.Validate if the designated constraints aren't met.
type WebLoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLoginReplyValidationError) ErrorName() string { return "WebLoginReplyValidationError" }

// Error satisfies the builtin error interface
func (e WebLoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLoginReplyValidationError{}

// Validate checks the field values on RoleItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleItemMultiError, or nil
// if none found.
func (m *RoleItem) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return RoleItemMultiError(errors)
	}

	return nil
}

// RoleItemMultiError is an error wrapping multiple validation errors returned
// by RoleItem.ValidateAll() if the designated constraints aren't met.
type RoleItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleItemMultiError) AllErrors() []error { return m }

// RoleItemValidationError is the validation error returned by
// RoleItem.Validate if the designated constraints aren't met.
type RoleItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleItemValidationError) ErrorName() string { return "RoleItemValidationError" }

// Error satisfies the builtin error interface
func (e RoleItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleItemValidationError{}

// Validate checks the field values on UserInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserInfoMultiError, or nil
// if none found.
func (m *UserInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	// no validation rules for Avatar

	// no validation rules for Gender

	// no validation rules for Birthday

	// no validation rules for Signature

	// no validation rules for Status

	if len(errors) > 0 {
		return UserInfoMultiError(errors)
	}

	return nil
}

// UserInfoMultiError is an error wrapping multiple validation errors returned
// by UserInfo.ValidateAll() if the designated constraints aren't met.
type UserInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserInfoMultiError) AllErrors() []error { return m }

// UserInfoValidationError is the validation error returned by
// UserInfo.Validate if the designated constraints aren't met.
type UserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserInfoValidationError) ErrorName() string { return "UserInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserInfoValidationError{}

// Validate checks the field values on UserPasswordInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserPasswordInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserPasswordInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserPasswordInfoMultiError, or nil if none found.
func (m *UserPasswordInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserPasswordInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Slat

	// no validation rules for Password

	if len(errors) > 0 {
		return UserPasswordInfoMultiError(errors)
	}

	return nil
}

// UserPasswordInfoMultiError is an error wrapping multiple validation errors
// returned by UserPasswordInfo.ValidateAll() if the designated constraints
// aren't met.
type UserPasswordInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserPasswordInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserPasswordInfoMultiError) AllErrors() []error { return m }

// UserPasswordInfoValidationError is the validation error returned by
// UserPasswordInfo.Validate if the designated constraints aren't met.
type UserPasswordInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserPasswordInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserPasswordInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserPasswordInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserPasswordInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserPasswordInfoValidationError) ErrorName() string { return "UserPasswordInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserPasswordInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserPasswordInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserPasswordInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserPasswordInfoValidationError{}

// Validate checks the field values on AppLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AppLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AppLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AppLoginRequestMultiError, or nil if none found.
func (m *AppLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AppLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AppLoginRequestMultiError(errors)
	}

	return nil
}

// AppLoginRequestMultiError is an error wrapping multiple validation errors
// returned by AppLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type AppLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AppLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AppLoginRequestMultiError) AllErrors() []error { return m }

// AppLoginRequestValidationError is the validation error returned by
// AppLoginRequest.Validate if the designated constraints aren't met.
type AppLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AppLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AppLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AppLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AppLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AppLoginRequestValidationError) ErrorName() string { return "AppLoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e AppLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAppLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AppLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AppLoginRequestValidationError{}

// Validate checks the field values on AppLoginReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AppLoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AppLoginReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AppLoginReplyMultiError, or
// nil if none found.
func (m *AppLoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AppLoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AppLoginReplyMultiError(errors)
	}

	return nil
}

// AppLoginReplyMultiError is an error wrapping multiple validation errors
// returned by AppLoginReply.ValidateAll() if the designated constraints
// aren't met.
type AppLoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AppLoginReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AppLoginReplyMultiError) AllErrors() []error { return m }

// AppLoginReplyValidationError is the validation error returned by
// AppLoginReply.Validate if the designated constraints aren't met.
type AppLoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AppLoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AppLoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AppLoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AppLoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AppLoginReplyValidationError) ErrorName() string { return "AppLoginReplyValidationError" }

// Error satisfies the builtin error interface
func (e AppLoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAppLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AppLoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AppLoginReplyValidationError{}

// Validate checks the field values on MpLoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MpLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MpLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MpLoginRequestMultiError,
// or nil if none found.
func (m *MpLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MpLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MpLoginRequestMultiError(errors)
	}

	return nil
}

// MpLoginRequestMultiError is an error wrapping multiple validation errors
// returned by MpLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type MpLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MpLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MpLoginRequestMultiError) AllErrors() []error { return m }

// MpLoginRequestValidationError is the validation error returned by
// MpLoginRequest.Validate if the designated constraints aren't met.
type MpLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MpLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MpLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MpLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MpLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MpLoginRequestValidationError) ErrorName() string { return "MpLoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e MpLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMpLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MpLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MpLoginRequestValidationError{}

// Validate checks the field values on MpLoginReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MpLoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MpLoginReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MpLoginReplyMultiError, or
// nil if none found.
func (m *MpLoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MpLoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MpLoginReplyMultiError(errors)
	}

	return nil
}

// MpLoginReplyMultiError is an error wrapping multiple validation errors
// returned by MpLoginReply.ValidateAll() if the designated constraints aren't met.
type MpLoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MpLoginReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MpLoginReplyMultiError) AllErrors() []error { return m }

// MpLoginReplyValidationError is the validation error returned by
// MpLoginReply.Validate if the designated constraints aren't met.
type MpLoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MpLoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MpLoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MpLoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MpLoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MpLoginReplyValidationError) ErrorName() string { return "MpLoginReplyValidationError" }

// Error satisfies the builtin error interface
func (e MpLoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMpLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MpLoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MpLoginReplyValidationError{}

// Validate checks the field values on GetWebLoginUserInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWebLoginUserInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWebLoginUserInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWebLoginUserInfoRequestMultiError, or nil if none found.
func (m *GetWebLoginUserInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWebLoginUserInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetWebLoginUserInfoRequestMultiError(errors)
	}

	return nil
}

// GetWebLoginUserInfoRequestMultiError is an error wrapping multiple
// validation errors returned by GetWebLoginUserInfoRequest.ValidateAll() if
// the designated constraints aren't met.
type GetWebLoginUserInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWebLoginUserInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWebLoginUserInfoRequestMultiError) AllErrors() []error { return m }

// GetWebLoginUserInfoRequestValidationError is the validation error returned
// by GetWebLoginUserInfoRequest.Validate if the designated constraints aren't met.
type GetWebLoginUserInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWebLoginUserInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWebLoginUserInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWebLoginUserInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWebLoginUserInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWebLoginUserInfoRequestValidationError) ErrorName() string {
	return "GetWebLoginUserInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetWebLoginUserInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWebLoginUserInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWebLoginUserInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWebLoginUserInfoRequestValidationError{}

// Validate checks the field values on WebLoginUserInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WebLoginUserInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLoginUserInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebLoginUserInfoMultiError, or nil if none found.
func (m *WebLoginUserInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLoginUserInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	// no validation rules for Avatar

	// no validation rules for Gender

	// no validation rules for Birthday

	// no validation rules for Signature

	if len(errors) > 0 {
		return WebLoginUserInfoMultiError(errors)
	}

	return nil
}

// WebLoginUserInfoMultiError is an error wrapping multiple validation errors
// returned by WebLoginUserInfo.ValidateAll() if the designated constraints
// aren't met.
type WebLoginUserInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLoginUserInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLoginUserInfoMultiError) AllErrors() []error { return m }

// WebLoginUserInfoValidationError is the validation error returned by
// WebLoginUserInfo.Validate if the designated constraints aren't met.
type WebLoginUserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLoginUserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLoginUserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLoginUserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLoginUserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLoginUserInfoValidationError) ErrorName() string { return "WebLoginUserInfoValidationError" }

// Error satisfies the builtin error interface
func (e WebLoginUserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLoginUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLoginUserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLoginUserInfoValidationError{}

// Validate checks the field values on GetWebLoginUserInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWebLoginUserInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWebLoginUserInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWebLoginUserInfoReplyMultiError, or nil if none found.
func (m *GetWebLoginUserInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWebLoginUserInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWebLoginUserInfoReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWebLoginUserInfoReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWebLoginUserInfoReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetWebLoginUserInfoReplyMultiError(errors)
	}

	return nil
}

// GetWebLoginUserInfoReplyMultiError is an error wrapping multiple validation
// errors returned by GetWebLoginUserInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetWebLoginUserInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWebLoginUserInfoReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWebLoginUserInfoReplyMultiError) AllErrors() []error { return m }

// GetWebLoginUserInfoReplyValidationError is the validation error returned by
// GetWebLoginUserInfoReply.Validate if the designated constraints aren't met.
type GetWebLoginUserInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWebLoginUserInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWebLoginUserInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWebLoginUserInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWebLoginUserInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWebLoginUserInfoReplyValidationError) ErrorName() string {
	return "GetWebLoginUserInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetWebLoginUserInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWebLoginUserInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWebLoginUserInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWebLoginUserInfoReplyValidationError{}

// Validate checks the field values on WebLogoutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WebLogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLogoutRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebLogoutRequestMultiError, or nil if none found.
func (m *WebLogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return WebLogoutRequestMultiError(errors)
	}

	return nil
}

// WebLogoutRequestMultiError is an error wrapping multiple validation errors
// returned by WebLogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type WebLogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLogoutRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLogoutRequestMultiError) AllErrors() []error { return m }

// WebLogoutRequestValidationError is the validation error returned by
// WebLogoutRequest.Validate if the designated constraints aren't met.
type WebLogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLogoutRequestValidationError) ErrorName() string { return "WebLogoutRequestValidationError" }

// Error satisfies the builtin error interface
func (e WebLogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLogoutRequestValidationError{}

// Validate checks the field values on WebLogoutReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebLogoutReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebLogoutReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebLogoutReplyMultiError,
// or nil if none found.
func (m *WebLogoutReply) ValidateAll() error {
	return m.validate(true)
}

func (m *WebLogoutReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return WebLogoutReplyMultiError(errors)
	}

	return nil
}

// WebLogoutReplyMultiError is an error wrapping multiple validation errors
// returned by WebLogoutReply.ValidateAll() if the designated constraints
// aren't met.
type WebLogoutReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebLogoutReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebLogoutReplyMultiError) AllErrors() []error { return m }

// WebLogoutReplyValidationError is the validation error returned by
// WebLogoutReply.Validate if the designated constraints aren't met.
type WebLogoutReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebLogoutReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebLogoutReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebLogoutReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebLogoutReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebLogoutReplyValidationError) ErrorName() string { return "WebLogoutReplyValidationError" }

// Error satisfies the builtin error interface
func (e WebLogoutReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebLogoutReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebLogoutReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebLogoutReplyValidationError{}

// Validate checks the field values on WebCheckLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WebCheckLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebCheckLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebCheckLoginRequestMultiError, or nil if none found.
func (m *WebCheckLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WebCheckLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return WebCheckLoginRequestMultiError(errors)
	}

	return nil
}

// WebCheckLoginRequestMultiError is an error wrapping multiple validation
// errors returned by WebCheckLoginRequest.ValidateAll() if the designated
// constraints aren't met.
type WebCheckLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebCheckLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebCheckLoginRequestMultiError) AllErrors() []error { return m }

// WebCheckLoginRequestValidationError is the validation error returned by
// WebCheckLoginRequest.Validate if the designated constraints aren't met.
type WebCheckLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebCheckLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebCheckLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebCheckLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebCheckLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebCheckLoginRequestValidationError) ErrorName() string {
	return "WebCheckLoginRequestValidationError"
}

// Error satisfies the builtin error interface
func (e WebCheckLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebCheckLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebCheckLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebCheckLoginRequestValidationError{}

// Validate checks the field values on WebCheckLoginReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WebCheckLoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebCheckLoginReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebCheckLoginReplyMultiError, or nil if none found.
func (m *WebCheckLoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *WebCheckLoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return WebCheckLoginReplyMultiError(errors)
	}

	return nil
}

// WebCheckLoginReplyMultiError is an error wrapping multiple validation errors
// returned by WebCheckLoginReply.ValidateAll() if the designated constraints
// aren't met.
type WebCheckLoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebCheckLoginReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebCheckLoginReplyMultiError) AllErrors() []error { return m }

// WebCheckLoginReplyValidationError is the validation error returned by
// WebCheckLoginReply.Validate if the designated constraints aren't met.
type WebCheckLoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebCheckLoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebCheckLoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebCheckLoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebCheckLoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebCheckLoginReplyValidationError) ErrorName() string {
	return "WebCheckLoginReplyValidationError"
}

// Error satisfies the builtin error interface
func (e WebCheckLoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebCheckLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebCheckLoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebCheckLoginReplyValidationError{}

// Validate checks the field values on UpdateUserBaseSettingRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserBaseSettingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserBaseSettingRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserBaseSettingRequestMultiError, or nil if none found.
func (m *UpdateUserBaseSettingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserBaseSettingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetNickname()); l < 1 || l > 20 {
		err := UpdateUserBaseSettingRequestValidationError{
			field:  "Nickname",
			reason: "value length must be between 1 and 20 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Gender

	if !_UpdateUserBaseSettingRequest_Birthday_Pattern.MatchString(m.GetBirthday()) {
		err := UpdateUserBaseSettingRequestValidationError{
			field:  "Birthday",
			reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSignature()); l < 0 || l > 100 {
		err := UpdateUserBaseSettingRequestValidationError{
			field:  "Signature",
			reason: "value length must be between 0 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateUserBaseSettingRequestMultiError(errors)
	}

	return nil
}

// UpdateUserBaseSettingRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateUserBaseSettingRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateUserBaseSettingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserBaseSettingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserBaseSettingRequestMultiError) AllErrors() []error { return m }

// UpdateUserBaseSettingRequestValidationError is the validation error returned
// by UpdateUserBaseSettingRequest.Validate if the designated constraints
// aren't met.
type UpdateUserBaseSettingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserBaseSettingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserBaseSettingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserBaseSettingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserBaseSettingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserBaseSettingRequestValidationError) ErrorName() string {
	return "UpdateUserBaseSettingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserBaseSettingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserBaseSettingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserBaseSettingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserBaseSettingRequestValidationError{}

var _UpdateUserBaseSettingRequest_Birthday_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$")

// Validate checks the field values on UpdateUserBaseSettingReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserBaseSettingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserBaseSettingReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserBaseSettingReplyMultiError, or nil if none found.
func (m *UpdateUserBaseSettingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserBaseSettingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return UpdateUserBaseSettingReplyMultiError(errors)
	}

	return nil
}

// UpdateUserBaseSettingReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateUserBaseSettingReply.ValidateAll() if
// the designated constraints aren't met.
type UpdateUserBaseSettingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserBaseSettingReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserBaseSettingReplyMultiError) AllErrors() []error { return m }

// UpdateUserBaseSettingReplyValidationError is the validation error returned
// by UpdateUserBaseSettingReply.Validate if the designated constraints aren't met.
type UpdateUserBaseSettingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserBaseSettingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserBaseSettingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserBaseSettingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserBaseSettingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserBaseSettingReplyValidationError) ErrorName() string {
	return "UpdateUserBaseSettingReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserBaseSettingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserBaseSettingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserBaseSettingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserBaseSettingReplyValidationError{}

// Validate checks the field values on UpdateUserPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserPasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserPasswordRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserPasswordRequestMultiError, or nil if none found.
func (m *UpdateUserPasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserPasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := len(m.GetPassword()); l < 6 || l > 32 {
		err := UpdateUserPasswordRequestValidationError{
			field:  "Password",
			reason: "value length must be between 6 and 32 bytes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UpdateUserPasswordRequest_Password_Pattern.MatchString(m.GetPassword()) {
		err := UpdateUserPasswordRequestValidationError{
			field:  "Password",
			reason: "value does not match regex pattern \"^.*[A-Za-z]+.*[0-9]+.*[^A-Za-z0-9]+.*$|^.*[0-9]+.*[A-Za-z]+.*[^A-Za-z0-9]+.*$|^.*[A-Za-z]+.*[^A-Za-z0-9]+.*[0-9]+.*$|^.*[0-9]+.*[^A-Za-z0-9]+.*[A-Za-z]+.*$|^.*[^A-Za-z0-9]+.*[A-Za-z]+.*[0-9]+.*$|^.*[^A-Za-z0-9]+.*[0-9]+.*[A-Za-z]+.*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateUserPasswordRequestMultiError(errors)
	}

	return nil
}

// UpdateUserPasswordRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateUserPasswordRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateUserPasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserPasswordRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserPasswordRequestMultiError) AllErrors() []error { return m }

// UpdateUserPasswordRequestValidationError is the validation error returned by
// UpdateUserPasswordRequest.Validate if the designated constraints aren't met.
type UpdateUserPasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserPasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserPasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserPasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserPasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserPasswordRequestValidationError) ErrorName() string {
	return "UpdateUserPasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserPasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserPasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserPasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserPasswordRequestValidationError{}

var _UpdateUserPasswordRequest_Password_Pattern = regexp.MustCompile("^.*[A-Za-z]+.*[0-9]+.*[^A-Za-z0-9]+.*$|^.*[0-9]+.*[A-Za-z]+.*[^A-Za-z0-9]+.*$|^.*[A-Za-z]+.*[^A-Za-z0-9]+.*[0-9]+.*$|^.*[0-9]+.*[^A-Za-z0-9]+.*[A-Za-z]+.*$|^.*[^A-Za-z0-9]+.*[A-Za-z]+.*[0-9]+.*$|^.*[^A-Za-z0-9]+.*[0-9]+.*[A-Za-z]+.*$")

// Validate checks the field values on UpdateUserPasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserPasswordReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserPasswordReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserPasswordReplyMultiError, or nil if none found.
func (m *UpdateUserPasswordReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserPasswordReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Success

	// no validation rules for Data

	if len(errors) > 0 {
		return UpdateUserPasswordReplyMultiError(errors)
	}

	return nil
}

// UpdateUserPasswordReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateUserPasswordReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateUserPasswordReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserPasswordReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserPasswordReplyMultiError) AllErrors() []error { return m }

// UpdateUserPasswordReplyValidationError is the validation error returned by
// UpdateUserPasswordReply.Validate if the designated constraints aren't met.
type UpdateUserPasswordReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserPasswordReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserPasswordReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserPasswordReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserPasswordReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserPasswordReplyValidationError) ErrorName() string {
	return "UpdateUserPasswordReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserPasswordReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserPasswordReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserPasswordReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserPasswordReplyValidationError{}
