// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: user/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_WebLogin_FullMethodName              = "/api.user.v1.User/WebLogin"
	User_WebCheckLogin_FullMethodName         = "/api.user.v1.User/WebCheckLogin"
	User_WebLogout_FullMethodName             = "/api.user.v1.User/WebLogout"
	User_AppLogin_FullMethodName              = "/api.user.v1.User/AppLogin"
	User_MpLogin_FullMethodName               = "/api.user.v1.User/MpLogin"
	User_GetWebLoginUserInfo_FullMethodName   = "/api.user.v1.User/GetWebLoginUserInfo"
	User_UpdateUserBaseSetting_FullMethodName = "/api.user.v1.User/UpdateUserBaseSetting"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// Web登录接口
	WebLogin(ctx context.Context, in *WebLoginRequest, opts ...grpc.CallOption) (*WebLoginReply, error)
	// Web登陆检测
	WebCheckLogin(ctx context.Context, in *WebCheckLoginRequest, opts ...grpc.CallOption) (*WebCheckLoginReply, error)
	WebLogout(ctx context.Context, in *WebLogoutRequest, opts ...grpc.CallOption) (*WebLogoutReply, error)
	// App登录
	AppLogin(ctx context.Context, in *AppLoginRequest, opts ...grpc.CallOption) (*AppLoginReply, error)
	// 小程序登录
	MpLogin(ctx context.Context, in *MpLoginRequest, opts ...grpc.CallOption) (*MpLoginReply, error)
	// 查询用户信息
	GetWebLoginUserInfo(ctx context.Context, in *GetWebLoginUserInfoRequest, opts ...grpc.CallOption) (*GetWebLoginUserInfoReply, error)
	// 更新基础设置
	UpdateUserBaseSetting(ctx context.Context, in *UpdateUserBaseSettingRequest, opts ...grpc.CallOption) (*UpdateUserBaseSettingReply, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) WebLogin(ctx context.Context, in *WebLoginRequest, opts ...grpc.CallOption) (*WebLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebLoginReply)
	err := c.cc.Invoke(ctx, User_WebLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) WebCheckLogin(ctx context.Context, in *WebCheckLoginRequest, opts ...grpc.CallOption) (*WebCheckLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebCheckLoginReply)
	err := c.cc.Invoke(ctx, User_WebCheckLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) WebLogout(ctx context.Context, in *WebLogoutRequest, opts ...grpc.CallOption) (*WebLogoutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebLogoutReply)
	err := c.cc.Invoke(ctx, User_WebLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AppLogin(ctx context.Context, in *AppLoginRequest, opts ...grpc.CallOption) (*AppLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppLoginReply)
	err := c.cc.Invoke(ctx, User_AppLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) MpLogin(ctx context.Context, in *MpLoginRequest, opts ...grpc.CallOption) (*MpLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MpLoginReply)
	err := c.cc.Invoke(ctx, User_MpLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetWebLoginUserInfo(ctx context.Context, in *GetWebLoginUserInfoRequest, opts ...grpc.CallOption) (*GetWebLoginUserInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebLoginUserInfoReply)
	err := c.cc.Invoke(ctx, User_GetWebLoginUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserBaseSetting(ctx context.Context, in *UpdateUserBaseSettingRequest, opts ...grpc.CallOption) (*UpdateUserBaseSettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserBaseSettingReply)
	err := c.cc.Invoke(ctx, User_UpdateUserBaseSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	// Web登录接口
	WebLogin(context.Context, *WebLoginRequest) (*WebLoginReply, error)
	// Web登陆检测
	WebCheckLogin(context.Context, *WebCheckLoginRequest) (*WebCheckLoginReply, error)
	WebLogout(context.Context, *WebLogoutRequest) (*WebLogoutReply, error)
	// App登录
	AppLogin(context.Context, *AppLoginRequest) (*AppLoginReply, error)
	// 小程序登录
	MpLogin(context.Context, *MpLoginRequest) (*MpLoginReply, error)
	// 查询用户信息
	GetWebLoginUserInfo(context.Context, *GetWebLoginUserInfoRequest) (*GetWebLoginUserInfoReply, error)
	// 更新基础设置
	UpdateUserBaseSetting(context.Context, *UpdateUserBaseSettingRequest) (*UpdateUserBaseSettingReply, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) WebLogin(context.Context, *WebLoginRequest) (*WebLoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WebLogin not implemented")
}
func (UnimplementedUserServer) WebCheckLogin(context.Context, *WebCheckLoginRequest) (*WebCheckLoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WebCheckLogin not implemented")
}
func (UnimplementedUserServer) WebLogout(context.Context, *WebLogoutRequest) (*WebLogoutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WebLogout not implemented")
}
func (UnimplementedUserServer) AppLogin(context.Context, *AppLoginRequest) (*AppLoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AppLogin not implemented")
}
func (UnimplementedUserServer) MpLogin(context.Context, *MpLoginRequest) (*MpLoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MpLogin not implemented")
}
func (UnimplementedUserServer) GetWebLoginUserInfo(context.Context, *GetWebLoginUserInfoRequest) (*GetWebLoginUserInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebLoginUserInfo not implemented")
}
func (UnimplementedUserServer) UpdateUserBaseSetting(context.Context, *UpdateUserBaseSettingRequest) (*UpdateUserBaseSettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBaseSetting not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_WebLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WebLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WebLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WebLogin(ctx, req.(*WebLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_WebCheckLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebCheckLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WebCheckLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WebCheckLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WebCheckLogin(ctx, req.(*WebCheckLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_WebLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WebLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WebLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WebLogout(ctx, req.(*WebLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AppLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AppLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AppLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AppLogin(ctx, req.(*AppLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_MpLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MpLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).MpLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_MpLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).MpLogin(ctx, req.(*MpLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetWebLoginUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebLoginUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetWebLoginUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetWebLoginUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetWebLoginUserInfo(ctx, req.(*GetWebLoginUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserBaseSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBaseSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserBaseSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserBaseSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserBaseSetting(ctx, req.(*UpdateUserBaseSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WebLogin",
			Handler:    _User_WebLogin_Handler,
		},
		{
			MethodName: "WebCheckLogin",
			Handler:    _User_WebCheckLogin_Handler,
		},
		{
			MethodName: "WebLogout",
			Handler:    _User_WebLogout_Handler,
		},
		{
			MethodName: "AppLogin",
			Handler:    _User_AppLogin_Handler,
		},
		{
			MethodName: "MpLogin",
			Handler:    _User_MpLogin_Handler,
		},
		{
			MethodName: "GetWebLoginUserInfo",
			Handler:    _User_GetWebLoginUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserBaseSetting",
			Handler:    _User_UpdateUserBaseSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
