// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserAppLogin = "/api.user.v1.User/AppLogin"
const OperationUserGetWebLoginUserInfo = "/api.user.v1.User/GetWebLoginUserInfo"
const OperationUserMpLogin = "/api.user.v1.User/MpLogin"
const OperationUserWebLogin = "/api.user.v1.User/WebLogin"

type UserHTTPServer interface {
	// AppLogin App登录
	AppLogin(context.Context, *AppLoginRequest) (*AppLoginReply, error)
	// GetWebLoginUserInfo 查询用户信息
	GetWebLoginUserInfo(context.Context, *GetWebLoginUserInfoRequest) (*GetWebLoginUserInfoReply, error)
	// MpLogin 小程序登录
	MpLogin(context.Context, *MpLoginRequest) (*MpLoginReply, error)
	// WebLogin Web登录接口
	WebLogin(context.Context, *WebLoginRequest) (*WebLoginReply, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/web/auth/login", _User_WebLogin0_HTTP_Handler(srv))
	r.POST("/api/v1/app/auth/login", _User_AppLogin0_HTTP_Handler(srv))
	r.POST("/api/v1/mp/auth/login", _User_MpLogin0_HTTP_Handler(srv))
	r.GET("/api/v1/web/user/info", _User_GetWebLoginUserInfo0_HTTP_Handler(srv))
}

func _User_WebLogin0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WebLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserWebLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WebLogin(ctx, req.(*WebLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WebLoginReply)
		return ctx.Result(200, reply)
	}
}

func _User_AppLogin0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AppLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserAppLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AppLogin(ctx, req.(*AppLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppLoginReply)
		return ctx.Result(200, reply)
	}
}

func _User_MpLogin0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MpLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserMpLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MpLogin(ctx, req.(*MpLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MpLoginReply)
		return ctx.Result(200, reply)
	}
}

func _User_GetWebLoginUserInfo0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWebLoginUserInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserGetWebLoginUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWebLoginUserInfo(ctx, req.(*GetWebLoginUserInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWebLoginUserInfoReply)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	// AppLogin App登录
	AppLogin(ctx context.Context, req *AppLoginRequest, opts ...http.CallOption) (rsp *AppLoginReply, err error)
	// GetWebLoginUserInfo 查询用户信息
	GetWebLoginUserInfo(ctx context.Context, req *GetWebLoginUserInfoRequest, opts ...http.CallOption) (rsp *GetWebLoginUserInfoReply, err error)
	// MpLogin 小程序登录
	MpLogin(ctx context.Context, req *MpLoginRequest, opts ...http.CallOption) (rsp *MpLoginReply, err error)
	// WebLogin Web登录接口
	WebLogin(ctx context.Context, req *WebLoginRequest, opts ...http.CallOption) (rsp *WebLoginReply, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

// AppLogin App登录
func (c *UserHTTPClientImpl) AppLogin(ctx context.Context, in *AppLoginRequest, opts ...http.CallOption) (*AppLoginReply, error) {
	var out AppLoginReply
	pattern := "/api/v1/app/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserAppLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWebLoginUserInfo 查询用户信息
func (c *UserHTTPClientImpl) GetWebLoginUserInfo(ctx context.Context, in *GetWebLoginUserInfoRequest, opts ...http.CallOption) (*GetWebLoginUserInfoReply, error) {
	var out GetWebLoginUserInfoReply
	pattern := "/api/v1/web/user/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserGetWebLoginUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MpLogin 小程序登录
func (c *UserHTTPClientImpl) MpLogin(ctx context.Context, in *MpLoginRequest, opts ...http.CallOption) (*MpLoginReply, error) {
	var out MpLoginReply
	pattern := "/api/v1/mp/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserMpLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WebLogin Web登录接口
func (c *UserHTTPClientImpl) WebLogin(ctx context.Context, in *WebLoginRequest, opts ...http.CallOption) (*WebLoginReply, error) {
	var out WebLoginReply
	pattern := "/api/v1/web/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserWebLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
