// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.9
// source: user/like/v1/like.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserLikeAddUserLike = "/api.user.like.v1.UserLike/AddUserLike"
const OperationUserLikeCancelUserLike = "/api.user.like.v1.UserLike/CancelUserLike"
const OperationUserLikeGetUserLikeStatus = "/api.user.like.v1.UserLike/GetUserLikeStatus"

type UserLikeHTTPServer interface {
	// AddUserLike AddUserLike 添加用户喜欢
	AddUserLike(context.Context, *AddUserLikeRequest) (*AddUserLikeReply, error)
	// CancelUserLike CancelUserLike 取消用户喜欢
	CancelUserLike(context.Context, *CancelUserLikeRequest) (*CancelUserLikeReply, error)
	// GetUserLikeStatus GetUserLikeStatus 查询用户喜欢状态
	GetUserLikeStatus(context.Context, *GetUserLikeStatusRequest) (*GetUserLikeStatusReply, error)
}

func RegisterUserLikeHTTPServer(s *http.Server, srv UserLikeHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/user/like/add", _UserLike_AddUserLike0_HTTP_Handler(srv))
	r.POST("/api/v1/user/like/cancel", _UserLike_CancelUserLike0_HTTP_Handler(srv))
	r.GET("/api/v1/user/like/status", _UserLike_GetUserLikeStatus0_HTTP_Handler(srv))
}

func _UserLike_AddUserLike0_HTTP_Handler(srv UserLikeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddUserLikeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLikeAddUserLike)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddUserLike(ctx, req.(*AddUserLikeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddUserLikeReply)
		return ctx.Result(200, reply)
	}
}

func _UserLike_CancelUserLike0_HTTP_Handler(srv UserLikeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelUserLikeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLikeCancelUserLike)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelUserLike(ctx, req.(*CancelUserLikeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelUserLikeReply)
		return ctx.Result(200, reply)
	}
}

func _UserLike_GetUserLikeStatus0_HTTP_Handler(srv UserLikeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserLikeStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLikeGetUserLikeStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserLikeStatus(ctx, req.(*GetUserLikeStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserLikeStatusReply)
		return ctx.Result(200, reply)
	}
}

type UserLikeHTTPClient interface {
	// AddUserLike AddUserLike 添加用户喜欢
	AddUserLike(ctx context.Context, req *AddUserLikeRequest, opts ...http.CallOption) (rsp *AddUserLikeReply, err error)
	// CancelUserLike CancelUserLike 取消用户喜欢
	CancelUserLike(ctx context.Context, req *CancelUserLikeRequest, opts ...http.CallOption) (rsp *CancelUserLikeReply, err error)
	// GetUserLikeStatus GetUserLikeStatus 查询用户喜欢状态
	GetUserLikeStatus(ctx context.Context, req *GetUserLikeStatusRequest, opts ...http.CallOption) (rsp *GetUserLikeStatusReply, err error)
}

type UserLikeHTTPClientImpl struct {
	cc *http.Client
}

func NewUserLikeHTTPClient(client *http.Client) UserLikeHTTPClient {
	return &UserLikeHTTPClientImpl{client}
}

// AddUserLike AddUserLike 添加用户喜欢
func (c *UserLikeHTTPClientImpl) AddUserLike(ctx context.Context, in *AddUserLikeRequest, opts ...http.CallOption) (*AddUserLikeReply, error) {
	var out AddUserLikeReply
	pattern := "/api/v1/user/like/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserLikeAddUserLike))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelUserLike CancelUserLike 取消用户喜欢
func (c *UserLikeHTTPClientImpl) CancelUserLike(ctx context.Context, in *CancelUserLikeRequest, opts ...http.CallOption) (*CancelUserLikeReply, error) {
	var out CancelUserLikeReply
	pattern := "/api/v1/user/like/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserLikeCancelUserLike))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserLikeStatus GetUserLikeStatus 查询用户喜欢状态
func (c *UserLikeHTTPClientImpl) GetUserLikeStatus(ctx context.Context, in *GetUserLikeStatusRequest, opts ...http.CallOption) (*GetUserLikeStatusReply, error) {
	var out GetUserLikeStatusReply
	pattern := "/api/v1/user/like/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserLikeGetUserLikeStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
