// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: user/setting/v1/setting.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserSetting_UpdateUserBaseSetting_FullMethodName           = "/api.user.setting.v1.UserSetting/UpdateUserBaseSetting"
	UserSetting_UpdateUserPassword_FullMethodName              = "/api.user.setting.v1.UserSetting/UpdateUserPassword"
	UserSetting_UpdateUserSystemNotifySetting_FullMethodName   = "/api.user.setting.v1.UserSetting/UpdateUserSystemNotifySetting"
	UserSetting_UpdateUserInteractNotifySetting_FullMethodName = "/api.user.setting.v1.UserSetting/UpdateUserInteractNotifySetting"
	UserSetting_UpdateUserAdoptNotifySetting_FullMethodName    = "/api.user.setting.v1.UserSetting/UpdateUserAdoptNotifySetting"
	UserSetting_UpdateUserEmailNotifySetting_FullMethodName    = "/api.user.setting.v1.UserSetting/UpdateUserEmailNotifySetting"
	UserSetting_GetUserNotifySetting_FullMethodName            = "/api.user.setting.v1.UserSetting/GetUserNotifySetting"
)

// UserSettingClient is the client API for UserSetting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSettingClient interface {
	// 更新基础更新
	UpdateUserBaseSetting(ctx context.Context, in *UpdateUserBaseSettingRequest, opts ...grpc.CallOption) (*UpdateUserBaseSettingReply, error)
	// 更新密码
	UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*UpdateUserPasswordReply, error)
	// UpdateUserSystemNotifySetting 更新用户系统通知
	UpdateUserSystemNotifySetting(ctx context.Context, in *UpdateUserSystemNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserSystemNotifySettingReply, error)
	// UpdateUserInteractNotifySetting 更新用户互动通知
	UpdateUserInteractNotifySetting(ctx context.Context, in *UpdateUserInteractNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserInteractNotifySettingReply, error)
	// UpdateUserAdoptNotifySetting 更新用户领养通知
	UpdateUserAdoptNotifySetting(ctx context.Context, in *UpdateUserAdoptNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserAdoptNotifySettingReply, error)
	// UpdateUserEmailNotifySetting 更新用户邮件通知
	UpdateUserEmailNotifySetting(ctx context.Context, in *UpdateUserEmailNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserEmailNotifySettingReply, error)
	// GetUserNotifySetting 获取用通知设置
	GetUserNotifySetting(ctx context.Context, in *GetUserNotifySettingRequest, opts ...grpc.CallOption) (*GetUserNotifySettingReply, error)
}

type userSettingClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSettingClient(cc grpc.ClientConnInterface) UserSettingClient {
	return &userSettingClient{cc}
}

func (c *userSettingClient) UpdateUserBaseSetting(ctx context.Context, in *UpdateUserBaseSettingRequest, opts ...grpc.CallOption) (*UpdateUserBaseSettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserBaseSettingReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserBaseSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*UpdateUserPasswordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserPasswordReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) UpdateUserSystemNotifySetting(ctx context.Context, in *UpdateUserSystemNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserSystemNotifySettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserSystemNotifySettingReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserSystemNotifySetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) UpdateUserInteractNotifySetting(ctx context.Context, in *UpdateUserInteractNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserInteractNotifySettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserInteractNotifySettingReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserInteractNotifySetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) UpdateUserAdoptNotifySetting(ctx context.Context, in *UpdateUserAdoptNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserAdoptNotifySettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserAdoptNotifySettingReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserAdoptNotifySetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) UpdateUserEmailNotifySetting(ctx context.Context, in *UpdateUserEmailNotifySettingRequest, opts ...grpc.CallOption) (*UpdateUserEmailNotifySettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserEmailNotifySettingReply)
	err := c.cc.Invoke(ctx, UserSetting_UpdateUserEmailNotifySetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingClient) GetUserNotifySetting(ctx context.Context, in *GetUserNotifySettingRequest, opts ...grpc.CallOption) (*GetUserNotifySettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotifySettingReply)
	err := c.cc.Invoke(ctx, UserSetting_GetUserNotifySetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSettingServer is the server API for UserSetting service.
// All implementations must embed UnimplementedUserSettingServer
// for forward compatibility.
type UserSettingServer interface {
	// 更新基础更新
	UpdateUserBaseSetting(context.Context, *UpdateUserBaseSettingRequest) (*UpdateUserBaseSettingReply, error)
	// 更新密码
	UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*UpdateUserPasswordReply, error)
	// UpdateUserSystemNotifySetting 更新用户系统通知
	UpdateUserSystemNotifySetting(context.Context, *UpdateUserSystemNotifySettingRequest) (*UpdateUserSystemNotifySettingReply, error)
	// UpdateUserInteractNotifySetting 更新用户互动通知
	UpdateUserInteractNotifySetting(context.Context, *UpdateUserInteractNotifySettingRequest) (*UpdateUserInteractNotifySettingReply, error)
	// UpdateUserAdoptNotifySetting 更新用户领养通知
	UpdateUserAdoptNotifySetting(context.Context, *UpdateUserAdoptNotifySettingRequest) (*UpdateUserAdoptNotifySettingReply, error)
	// UpdateUserEmailNotifySetting 更新用户邮件通知
	UpdateUserEmailNotifySetting(context.Context, *UpdateUserEmailNotifySettingRequest) (*UpdateUserEmailNotifySettingReply, error)
	// GetUserNotifySetting 获取用通知设置
	GetUserNotifySetting(context.Context, *GetUserNotifySettingRequest) (*GetUserNotifySettingReply, error)
	mustEmbedUnimplementedUserSettingServer()
}

// UnimplementedUserSettingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserSettingServer struct{}

func (UnimplementedUserSettingServer) UpdateUserBaseSetting(context.Context, *UpdateUserBaseSettingRequest) (*UpdateUserBaseSettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBaseSetting not implemented")
}
func (UnimplementedUserSettingServer) UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*UpdateUserPasswordReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPassword not implemented")
}
func (UnimplementedUserSettingServer) UpdateUserSystemNotifySetting(context.Context, *UpdateUserSystemNotifySettingRequest) (*UpdateUserSystemNotifySettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserSystemNotifySetting not implemented")
}
func (UnimplementedUserSettingServer) UpdateUserInteractNotifySetting(context.Context, *UpdateUserInteractNotifySettingRequest) (*UpdateUserInteractNotifySettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserInteractNotifySetting not implemented")
}
func (UnimplementedUserSettingServer) UpdateUserAdoptNotifySetting(context.Context, *UpdateUserAdoptNotifySettingRequest) (*UpdateUserAdoptNotifySettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserAdoptNotifySetting not implemented")
}
func (UnimplementedUserSettingServer) UpdateUserEmailNotifySetting(context.Context, *UpdateUserEmailNotifySettingRequest) (*UpdateUserEmailNotifySettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserEmailNotifySetting not implemented")
}
func (UnimplementedUserSettingServer) GetUserNotifySetting(context.Context, *GetUserNotifySettingRequest) (*GetUserNotifySettingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotifySetting not implemented")
}
func (UnimplementedUserSettingServer) mustEmbedUnimplementedUserSettingServer() {}
func (UnimplementedUserSettingServer) testEmbeddedByValue()                     {}

// UnsafeUserSettingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSettingServer will
// result in compilation errors.
type UnsafeUserSettingServer interface {
	mustEmbedUnimplementedUserSettingServer()
}

func RegisterUserSettingServer(s grpc.ServiceRegistrar, srv UserSettingServer) {
	// If the following call panics, it indicates UnimplementedUserSettingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserSetting_ServiceDesc, srv)
}

func _UserSetting_UpdateUserBaseSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBaseSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserBaseSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserBaseSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserBaseSetting(ctx, req.(*UpdateUserBaseSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserPassword(ctx, req.(*UpdateUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_UpdateUserSystemNotifySetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserSystemNotifySettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserSystemNotifySetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserSystemNotifySetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserSystemNotifySetting(ctx, req.(*UpdateUserSystemNotifySettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_UpdateUserInteractNotifySetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInteractNotifySettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserInteractNotifySetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserInteractNotifySetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserInteractNotifySetting(ctx, req.(*UpdateUserInteractNotifySettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_UpdateUserAdoptNotifySetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAdoptNotifySettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserAdoptNotifySetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserAdoptNotifySetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserAdoptNotifySetting(ctx, req.(*UpdateUserAdoptNotifySettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_UpdateUserEmailNotifySetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserEmailNotifySettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).UpdateUserEmailNotifySetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_UpdateUserEmailNotifySetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).UpdateUserEmailNotifySetting(ctx, req.(*UpdateUserEmailNotifySettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSetting_GetUserNotifySetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotifySettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingServer).GetUserNotifySetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSetting_GetUserNotifySetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingServer).GetUserNotifySetting(ctx, req.(*GetUserNotifySettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSetting_ServiceDesc is the grpc.ServiceDesc for UserSetting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSetting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.setting.v1.UserSetting",
	HandlerType: (*UserSettingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUserBaseSetting",
			Handler:    _UserSetting_UpdateUserBaseSetting_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _UserSetting_UpdateUserPassword_Handler,
		},
		{
			MethodName: "UpdateUserSystemNotifySetting",
			Handler:    _UserSetting_UpdateUserSystemNotifySetting_Handler,
		},
		{
			MethodName: "UpdateUserInteractNotifySetting",
			Handler:    _UserSetting_UpdateUserInteractNotifySetting_Handler,
		},
		{
			MethodName: "UpdateUserAdoptNotifySetting",
			Handler:    _UserSetting_UpdateUserAdoptNotifySetting_Handler,
		},
		{
			MethodName: "UpdateUserEmailNotifySetting",
			Handler:    _UserSetting_UpdateUserEmailNotifySetting_Handler,
		},
		{
			MethodName: "GetUserNotifySetting",
			Handler:    _UserSetting_GetUserNotifySetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/setting/v1/setting.proto",
}
