// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.9
// source: file/v1/file.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFileDownloadFile = "/api.file.v1.File/DownloadFile"
const OperationFileGetStaticFile = "/api.file.v1.File/GetStaticFile"
const OperationFileUploadAvatar = "/api.file.v1.File/UploadAvatar"

type FileHTTPServer interface {
	// DownloadFile 下载文件
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error)
	// GetStaticFile GetStaticFile
	GetStaticFile(context.Context, *StaticFileRequest) (*StaticFileReply, error)
	// UploadAvatar 上传头像
	UploadAvatar(context.Context, *UploadAvatarRequest) (*UploadAvatarReply, error)
}

func RegisterFileHTTPServer(s *http.Server, srv FileHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/file/download", _File_DownloadFile0_HTTP_Handler(srv))
	r.POST("/api/v1/user/avatar/upload", _File_UploadAvatar0_HTTP_Handler(srv))
	r.GET("/static/{filename}", _File_GetStaticFile0_HTTP_Handler(srv))
}

func _File_DownloadFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileDownloadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadFile(ctx, req.(*DownloadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DownloadFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_UploadAvatar0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadAvatarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileUploadAvatar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadAvatar(ctx, req.(*UploadAvatarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadAvatarReply)
		return ctx.Result(200, reply)
	}
}

func _File_GetStaticFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StaticFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileGetStaticFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStaticFile(ctx, req.(*StaticFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StaticFileReply)
		return ctx.Result(200, reply)
	}
}

type FileHTTPClient interface {
	// DownloadFile 下载文件
	DownloadFile(ctx context.Context, req *DownloadFileRequest, opts ...http.CallOption) (rsp *DownloadFileReply, err error)
	// GetStaticFile GetStaticFile
	GetStaticFile(ctx context.Context, req *StaticFileRequest, opts ...http.CallOption) (rsp *StaticFileReply, err error)
	// UploadAvatar 上传头像
	UploadAvatar(ctx context.Context, req *UploadAvatarRequest, opts ...http.CallOption) (rsp *UploadAvatarReply, err error)
}

type FileHTTPClientImpl struct {
	cc *http.Client
}

func NewFileHTTPClient(client *http.Client) FileHTTPClient {
	return &FileHTTPClientImpl{client}
}

// DownloadFile 下载文件
func (c *FileHTTPClientImpl) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...http.CallOption) (*DownloadFileReply, error) {
	var out DownloadFileReply
	pattern := "/api/v1/file/download"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileDownloadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStaticFile GetStaticFile
func (c *FileHTTPClientImpl) GetStaticFile(ctx context.Context, in *StaticFileRequest, opts ...http.CallOption) (*StaticFileReply, error) {
	var out StaticFileReply
	pattern := "/static/{filename}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileGetStaticFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadAvatar 上传头像
func (c *FileHTTPClientImpl) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...http.CallOption) (*UploadAvatarReply, error) {
	var out UploadAvatarReply
	pattern := "/api/v1/user/avatar/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileUploadAvatar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
