// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: publish/v1/publish.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPublishCreatePublish = "/api.publish.v1.Publish/CreatePublish"
const OperationPublishDeletePublish = "/api.publish.v1.Publish/DeletePublish"
const OperationPublishGetPublishList = "/api.publish.v1.Publish/GetPublishList"
const OperationPublishUpdatePublish = "/api.publish.v1.Publish/UpdatePublish"
const OperationPublishUpdatePublishStatus = "/api.publish.v1.Publish/UpdatePublishStatus"

type PublishHTTPServer interface {
	// CreatePublish CreatePublish 创建发布内容
	CreatePublish(context.Context, *CreatePublishRequest) (*CreatePublishReply, error)
	// DeletePublish DeletePublish 删除发布内容
	DeletePublish(context.Context, *DeletePublishRequest) (*DeletePublishReply, error)
	// GetPublishList GetPublishList 查询发布内容列表
	GetPublishList(context.Context, *GetPublishListRequest) (*GetPublishListReply, error)
	// UpdatePublish UpdateUser 更新发布内容
	UpdatePublish(context.Context, *UpdatePublishRequest) (*UpdatePublishReply, error)
	// UpdatePublishStatus UpdatePublishStatus 更新发布内容状态
	UpdatePublishStatus(context.Context, *UpdatePublishStatusRequest) (*UpdatePublishStatusReply, error)
}

func RegisterPublishHTTPServer(s *http.Server, srv PublishHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/publish/list", _Publish_GetPublishList0_HTTP_Handler(srv))
	r.POST("/api/v1/publish", _Publish_CreatePublish0_HTTP_Handler(srv))
	r.PUT("/api/v1/publish/{id}", _Publish_UpdatePublish0_HTTP_Handler(srv))
	r.DELETE("/api/v1/publish/{id}", _Publish_DeletePublish0_HTTP_Handler(srv))
	r.PUT("/api/v1/publish/status/{id}", _Publish_UpdatePublishStatus0_HTTP_Handler(srv))
}

func _Publish_GetPublishList0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPublishListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishGetPublishList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPublishList(ctx, req.(*GetPublishListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPublishListReply)
		return ctx.Result(200, reply)
	}
}

func _Publish_CreatePublish0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePublishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishCreatePublish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePublish(ctx, req.(*CreatePublishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePublishReply)
		return ctx.Result(200, reply)
	}
}

func _Publish_UpdatePublish0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePublishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishUpdatePublish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePublish(ctx, req.(*UpdatePublishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePublishReply)
		return ctx.Result(200, reply)
	}
}

func _Publish_DeletePublish0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePublishRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishDeletePublish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePublish(ctx, req.(*DeletePublishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePublishReply)
		return ctx.Result(200, reply)
	}
}

func _Publish_UpdatePublishStatus0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePublishStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishUpdatePublishStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePublishStatus(ctx, req.(*UpdatePublishStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePublishStatusReply)
		return ctx.Result(200, reply)
	}
}

type PublishHTTPClient interface {
	// CreatePublish CreatePublish 创建发布内容
	CreatePublish(ctx context.Context, req *CreatePublishRequest, opts ...http.CallOption) (rsp *CreatePublishReply, err error)
	// DeletePublish DeletePublish 删除发布内容
	DeletePublish(ctx context.Context, req *DeletePublishRequest, opts ...http.CallOption) (rsp *DeletePublishReply, err error)
	// GetPublishList GetPublishList 查询发布内容列表
	GetPublishList(ctx context.Context, req *GetPublishListRequest, opts ...http.CallOption) (rsp *GetPublishListReply, err error)
	// UpdatePublish UpdateUser 更新发布内容
	UpdatePublish(ctx context.Context, req *UpdatePublishRequest, opts ...http.CallOption) (rsp *UpdatePublishReply, err error)
	// UpdatePublishStatus UpdatePublishStatus 更新发布内容状态
	UpdatePublishStatus(ctx context.Context, req *UpdatePublishStatusRequest, opts ...http.CallOption) (rsp *UpdatePublishStatusReply, err error)
}

type PublishHTTPClientImpl struct {
	cc *http.Client
}

func NewPublishHTTPClient(client *http.Client) PublishHTTPClient {
	return &PublishHTTPClientImpl{client}
}

// CreatePublish CreatePublish 创建发布内容
func (c *PublishHTTPClientImpl) CreatePublish(ctx context.Context, in *CreatePublishRequest, opts ...http.CallOption) (*CreatePublishReply, error) {
	var out CreatePublishReply
	pattern := "/api/v1/publish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublishCreatePublish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePublish DeletePublish 删除发布内容
func (c *PublishHTTPClientImpl) DeletePublish(ctx context.Context, in *DeletePublishRequest, opts ...http.CallOption) (*DeletePublishReply, error) {
	var out DeletePublishReply
	pattern := "/api/v1/publish/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublishDeletePublish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPublishList GetPublishList 查询发布内容列表
func (c *PublishHTTPClientImpl) GetPublishList(ctx context.Context, in *GetPublishListRequest, opts ...http.CallOption) (*GetPublishListReply, error) {
	var out GetPublishListReply
	pattern := "/api/v1/publish/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPublishGetPublishList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePublish UpdateUser 更新发布内容
func (c *PublishHTTPClientImpl) UpdatePublish(ctx context.Context, in *UpdatePublishRequest, opts ...http.CallOption) (*UpdatePublishReply, error) {
	var out UpdatePublishReply
	pattern := "/api/v1/publish/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublishUpdatePublish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePublishStatus UpdatePublishStatus 更新发布内容状态
func (c *PublishHTTPClientImpl) UpdatePublishStatus(ctx context.Context, in *UpdatePublishStatusRequest, opts ...http.CallOption) (*UpdatePublishStatusReply, error) {
	var out UpdatePublishStatusReply
	pattern := "/api/v1/publish/status/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublishUpdatePublishStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
