// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: user/collect/v1/collect.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserCollectGetUserCollectList = "/api.user.collect.v1.UserCollect/GetUserCollectList"
const OperationUserCollectGetUserCollectTypes = "/api.user.collect.v1.UserCollect/GetUserCollectTypes"

type UserCollectHTTPServer interface {
	// GetUserCollectList GetUserCollectList 查询用户收藏列表
	GetUserCollectList(context.Context, *GetUserCollectListRequest) (*GetUserCollectListReply, error)
	// GetUserCollectTypes GetUserCollectTypes 查询用户收藏分类
	GetUserCollectTypes(context.Context, *GetUserCollectTypesRequest) (*GetUserCollectTypesReply, error)
}

func RegisterUserCollectHTTPServer(s *http.Server, srv UserCollectHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/user/collect/list", _UserCollect_GetUserCollectList0_HTTP_Handler(srv))
	r.GET("/api/v1/user/collect/types", _UserCollect_GetUserCollectTypes0_HTTP_Handler(srv))
}

func _UserCollect_GetUserCollectList0_HTTP_Handler(srv UserCollectHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserCollectListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCollectGetUserCollectList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserCollectList(ctx, req.(*GetUserCollectListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserCollectListReply)
		return ctx.Result(200, reply)
	}
}

func _UserCollect_GetUserCollectTypes0_HTTP_Handler(srv UserCollectHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserCollectTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCollectGetUserCollectTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserCollectTypes(ctx, req.(*GetUserCollectTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserCollectTypesReply)
		return ctx.Result(200, reply)
	}
}

type UserCollectHTTPClient interface {
	// GetUserCollectList GetUserCollectList 查询用户收藏列表
	GetUserCollectList(ctx context.Context, req *GetUserCollectListRequest, opts ...http.CallOption) (rsp *GetUserCollectListReply, err error)
	// GetUserCollectTypes GetUserCollectTypes 查询用户收藏分类
	GetUserCollectTypes(ctx context.Context, req *GetUserCollectTypesRequest, opts ...http.CallOption) (rsp *GetUserCollectTypesReply, err error)
}

type UserCollectHTTPClientImpl struct {
	cc *http.Client
}

func NewUserCollectHTTPClient(client *http.Client) UserCollectHTTPClient {
	return &UserCollectHTTPClientImpl{client}
}

// GetUserCollectList GetUserCollectList 查询用户收藏列表
func (c *UserCollectHTTPClientImpl) GetUserCollectList(ctx context.Context, in *GetUserCollectListRequest, opts ...http.CallOption) (*GetUserCollectListReply, error) {
	var out GetUserCollectListReply
	pattern := "/api/v1/user/collect/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCollectGetUserCollectList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserCollectTypes GetUserCollectTypes 查询用户收藏分类
func (c *UserCollectHTTPClientImpl) GetUserCollectTypes(ctx context.Context, in *GetUserCollectTypesRequest, opts ...http.CallOption) (*GetUserCollectTypesReply, error) {
	var out GetUserCollectTypesReply
	pattern := "/api/v1/user/collect/types"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCollectGetUserCollectTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
