// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/contrib/registry/nacos/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xiaomiao-home-system/internal/biz"
	"xiaomiao-home-system/internal/conf"
	"xiaomiao-home-system/internal/data"
	"xiaomiao-home-system/internal/server"
	"xiaomiao-home-system/internal/service"
	"xiaomiao-home-system/internal/task"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, config *conf.Config, jwt *conf.Jwt, static *conf.Static, registry *nacos.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, config, static, jwt, logger)
	if err != nil {
		return nil, nil, err
	}
	taskManager := task.NewTaskManager(config, dataData, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, config, logger)
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, logger)
	roleService := service.NewRoleService(roleUsecase, config, logger)
	userNotificationRepo := data.NewUserNotificationRepo(dataData, logger)
	userNotificationUsecase := biz.NewUserNotificationUsecase(userNotificationRepo, logger)
	userNotificationService := service.NewUserNotificationService(userNotificationUsecase, config, logger)
	userSettingRepo := data.NewUserSettingRepo(dataData, logger)
	userSettingUsecase := biz.NewUserSettingUsecase(userSettingRepo, logger)
	userSettingService := service.NewUserSettingService(userSettingUsecase, config, logger)
	fileRepo := data.NewFileRepo(dataData, logger)
	fileUsecase := biz.NewFileUsecase(fileRepo, logger)
	fileService := service.NewFileService(fileUsecase, config, static, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, roleService, userNotificationService, userSettingService, fileService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, static, userService, roleService, userNotificationService, userSettingService, fileService, logger)
	app := newApp(logger, taskManager, grpcServer, httpServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
