// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: cat/v1/collect.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCatGetCatList = "/api.cat.v1.Cat/GetCatList"

type CatHTTPServer interface {
	// GetCatList GetCatList 查询小猫列表
	GetCatList(context.Context, *GetCatListRequest) (*GetCatListReply, error)
}

func RegisterCatHTTPServer(s *http.Server, srv CatHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/cat/list", _Cat_GetCatList0_HTTP_Handler(srv))
}

func _Cat_GetCatList0_HTTP_Handler(srv CatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCatListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCatGetCatList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCatList(ctx, req.(*GetCatListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCatListReply)
		return ctx.Result(200, reply)
	}
}

type CatHTTPClient interface {
	// GetCatList GetCatList 查询小猫列表
	GetCatList(ctx context.Context, req *GetCatListRequest, opts ...http.CallOption) (rsp *GetCatListReply, err error)
}

type CatHTTPClientImpl struct {
	cc *http.Client
}

func NewCatHTTPClient(client *http.Client) CatHTTPClient {
	return &CatHTTPClientImpl{client}
}

// GetCatList GetCatList 查询小猫列表
func (c *CatHTTPClientImpl) GetCatList(ctx context.Context, in *GetCatListRequest, opts ...http.CallOption) (*GetCatListReply, error) {
	var out GetCatListReply
	pattern := "/api/v1/cat/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCatGetCatList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
