// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cat/v1/collect.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础请求体
type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_cat_v1_collect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{0}
}

// 基础响应体
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_cat_v1_collect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{1}
}

type GetCatListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	CType         int32                  `protobuf:"varint,3,opt,name=c_type,json=cType,proto3" json:"c_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatListRequest) Reset() {
	*x = GetCatListRequest{}
	mi := &file_cat_v1_collect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatListRequest) ProtoMessage() {}

func (x *GetCatListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatListRequest.ProtoReflect.Descriptor instead.
func (*GetCatListRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCatListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetCatListRequest) GetCType() int32 {
	if x != nil {
		return x.CType
	}
	return 0
}

type CatListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PostStatus    int32                  `protobuf:"varint,3,opt,name=postStatus,proto3" json:"postStatus,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,4,opt,name=auditStatus,proto3" json:"auditStatus,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,8,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatListItem) Reset() {
	*x = CatListItem{}
	mi := &file_cat_v1_collect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatListItem) ProtoMessage() {}

func (x *CatListItem) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatListItem.ProtoReflect.Descriptor instead.
func (*CatListItem) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{3}
}

func (x *CatListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CatListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CatListItem) GetPostStatus() int32 {
	if x != nil {
		return x.PostStatus
	}
	return 0
}

func (x *CatListItem) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *CatListItem) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CatListItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CatListItem) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *CatListItem) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type CatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatListItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatList) Reset() {
	*x = CatList{}
	mi := &file_cat_v1_collect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatList) ProtoMessage() {}

func (x *CatList) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatList.ProtoReflect.Descriptor instead.
func (*CatList) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{4}
}

func (x *CatList) GetItems() []*CatListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CatList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCatListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Data          *CatList               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatListReply) Reset() {
	*x = GetCatListReply{}
	mi := &file_cat_v1_collect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatListReply) ProtoMessage() {}

func (x *GetCatListReply) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_collect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatListReply.ProtoReflect.Descriptor instead.
func (*GetCatListReply) Descriptor() ([]byte, []int) {
	return file_cat_v1_collect_proto_rawDescGZIP(), []int{5}
}

func (x *GetCatListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCatListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCatListReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCatListReply) GetData() *CatList {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cat_v1_collect_proto protoreflect.FileDescriptor

const file_cat_v1_collect_proto_rawDesc = "" +
	"\n" +
	"\x14cat/v1/collect.proto\x12\n" +
	"api.cat.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\r\n" +
	"\vBaseRequest\"\x0e\n" +
	"\fBaseResponse\"r\n" +
	"\x11GetCatListRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12\x1e\n" +
	"\x04size\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xc8\x01(\n" +
	"R\x04size\x12 \n" +
	"\x06c_type\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x14(\x00R\x05cType\"\xf1\x01\n" +
	"\vCatListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"postStatus\x18\x03 \x01(\x05R\n" +
	"postStatus\x12 \n" +
	"\vauditStatus\x18\x04 \x01(\x05R\vauditStatus\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12 \n" +
	"\vcreatedTime\x18\a \x01(\tR\vcreatedTime\x12 \n" +
	"\vupdatedTime\x18\b \x01(\tR\vupdatedTime\"N\n" +
	"\aCatList\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.api.cat.v1.CatListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x82\x01\n" +
	"\x0fGetCatListReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12'\n" +
	"\x04data\x18\x04 \x01(\v2\x13.api.cat.v1.CatListR\x04data2i\n" +
	"\x03Cat\x12b\n" +
	"\n" +
	"GetCatList\x12\x1d.api.cat.v1.GetCatListRequest\x1a\x1b.api.cat.v1.GetCatListReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/cat/listB>\n" +
	"\n" +
	"api.cat.v1B\n" +
	"CatProtoV1P\x01Z\"xiaomiao-home-system/api/cat/v1;v1b\x06proto3"

var (
	file_cat_v1_collect_proto_rawDescOnce sync.Once
	file_cat_v1_collect_proto_rawDescData []byte
)

func file_cat_v1_collect_proto_rawDescGZIP() []byte {
	file_cat_v1_collect_proto_rawDescOnce.Do(func() {
		file_cat_v1_collect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cat_v1_collect_proto_rawDesc), len(file_cat_v1_collect_proto_rawDesc)))
	})
	return file_cat_v1_collect_proto_rawDescData
}

var file_cat_v1_collect_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cat_v1_collect_proto_goTypes = []any{
	(*BaseRequest)(nil),       // 0: api.cat.v1.BaseRequest
	(*BaseResponse)(nil),      // 1: api.cat.v1.BaseResponse
	(*GetCatListRequest)(nil), // 2: api.cat.v1.GetCatListRequest
	(*CatListItem)(nil),       // 3: api.cat.v1.CatListItem
	(*CatList)(nil),           // 4: api.cat.v1.CatList
	(*GetCatListReply)(nil),   // 5: api.cat.v1.GetCatListReply
}
var file_cat_v1_collect_proto_depIdxs = []int32{
	3, // 0: api.cat.v1.CatList.items:type_name -> api.cat.v1.CatListItem
	4, // 1: api.cat.v1.GetCatListReply.data:type_name -> api.cat.v1.CatList
	2, // 2: api.cat.v1.Cat.GetCatList:input_type -> api.cat.v1.GetCatListRequest
	5, // 3: api.cat.v1.Cat.GetCatList:output_type -> api.cat.v1.GetCatListReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cat_v1_collect_proto_init() }
func file_cat_v1_collect_proto_init() {
	if File_cat_v1_collect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cat_v1_collect_proto_rawDesc), len(file_cat_v1_collect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_v1_collect_proto_goTypes,
		DependencyIndexes: file_cat_v1_collect_proto_depIdxs,
		MessageInfos:      file_cat_v1_collect_proto_msgTypes,
	}.Build()
	File_cat_v1_collect_proto = out.File
	file_cat_v1_collect_proto_goTypes = nil
	file_cat_v1_collect_proto_depIdxs = nil
}
