// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: user/notification/v1/notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserNotificationBatchUserNotifications = "/api.user.notification.v1.UserNotification/BatchUserNotifications"
const OperationUserNotificationDeleteUserNotification = "/api.user.notification.v1.UserNotification/DeleteUserNotification"
const OperationUserNotificationGetUserNotificationList = "/api.user.notification.v1.UserNotification/GetUserNotificationList"
const OperationUserNotificationUpdateUserAllNotificationStatus = "/api.user.notification.v1.UserNotification/UpdateUserAllNotificationStatus"
const OperationUserNotificationUpdateUserNotificationStatus = "/api.user.notification.v1.UserNotification/UpdateUserNotificationStatus"

type UserNotificationHTTPServer interface {
	// BatchUserNotifications BatchUserNotifications 批量操作
	BatchUserNotifications(context.Context, *BatchUserNotificationsRequest) (*BatchUserNotificationsReply, error)
	// DeleteUserNotification DeleteUserNotification 删除用户消息
	DeleteUserNotification(context.Context, *DeleteUserNotificationRequest) (*DeleteUserNotificationReply, error)
	// GetUserNotificationList GetUserNotificationList 查询用户消息列表
	GetUserNotificationList(context.Context, *GetUserNotificationListRequest) (*GetUserNotificationListReply, error)
	// UpdateUserAllNotificationStatus UpdateUserAllNotificationStatus 更新所有消息已读
	UpdateUserAllNotificationStatus(context.Context, *UpdateUserAllNotificationStatusRequest) (*UpdateUserAllNotificationStatusReply, error)
	// UpdateUserNotificationStatus UpdateUserNotificationStatus 更新用户消息状态
	UpdateUserNotificationStatus(context.Context, *UpdateUserNotificationStatusRequest) (*UpdateUserNotificationStatusReply, error)
}

func RegisterUserNotificationHTTPServer(s *http.Server, srv UserNotificationHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/user/notification/list", _UserNotification_GetUserNotificationList0_HTTP_Handler(srv))
	r.DELETE("/api/v1/user/notification/{id}", _UserNotification_DeleteUserNotification0_HTTP_Handler(srv))
	r.PUT("/api/v1/user/notification/status/{id}", _UserNotification_UpdateUserNotificationStatus0_HTTP_Handler(srv))
	r.POST("/api/v1/user/notification/batch", _UserNotification_BatchUserNotifications0_HTTP_Handler(srv))
	r.POST("/api/v1/user/notification", _UserNotification_UpdateUserAllNotificationStatus0_HTTP_Handler(srv))
}

func _UserNotification_GetUserNotificationList0_HTTP_Handler(srv UserNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserNotificationListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserNotificationGetUserNotificationList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserNotificationList(ctx, req.(*GetUserNotificationListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserNotificationListReply)
		return ctx.Result(200, reply)
	}
}

func _UserNotification_DeleteUserNotification0_HTTP_Handler(srv UserNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserNotificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserNotificationDeleteUserNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUserNotification(ctx, req.(*DeleteUserNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteUserNotificationReply)
		return ctx.Result(200, reply)
	}
}

func _UserNotification_UpdateUserNotificationStatus0_HTTP_Handler(srv UserNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserNotificationStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserNotificationUpdateUserNotificationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserNotificationStatus(ctx, req.(*UpdateUserNotificationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserNotificationStatusReply)
		return ctx.Result(200, reply)
	}
}

func _UserNotification_BatchUserNotifications0_HTTP_Handler(srv UserNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchUserNotificationsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserNotificationBatchUserNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchUserNotifications(ctx, req.(*BatchUserNotificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchUserNotificationsReply)
		return ctx.Result(200, reply)
	}
}

func _UserNotification_UpdateUserAllNotificationStatus0_HTTP_Handler(srv UserNotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserAllNotificationStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserNotificationUpdateUserAllNotificationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserAllNotificationStatus(ctx, req.(*UpdateUserAllNotificationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserAllNotificationStatusReply)
		return ctx.Result(200, reply)
	}
}

type UserNotificationHTTPClient interface {
	// BatchUserNotifications BatchUserNotifications 批量操作
	BatchUserNotifications(ctx context.Context, req *BatchUserNotificationsRequest, opts ...http.CallOption) (rsp *BatchUserNotificationsReply, err error)
	// DeleteUserNotification DeleteUserNotification 删除用户消息
	DeleteUserNotification(ctx context.Context, req *DeleteUserNotificationRequest, opts ...http.CallOption) (rsp *DeleteUserNotificationReply, err error)
	// GetUserNotificationList GetUserNotificationList 查询用户消息列表
	GetUserNotificationList(ctx context.Context, req *GetUserNotificationListRequest, opts ...http.CallOption) (rsp *GetUserNotificationListReply, err error)
	// UpdateUserAllNotificationStatus UpdateUserAllNotificationStatus 更新所有消息已读
	UpdateUserAllNotificationStatus(ctx context.Context, req *UpdateUserAllNotificationStatusRequest, opts ...http.CallOption) (rsp *UpdateUserAllNotificationStatusReply, err error)
	// UpdateUserNotificationStatus UpdateUserNotificationStatus 更新用户消息状态
	UpdateUserNotificationStatus(ctx context.Context, req *UpdateUserNotificationStatusRequest, opts ...http.CallOption) (rsp *UpdateUserNotificationStatusReply, err error)
}

type UserNotificationHTTPClientImpl struct {
	cc *http.Client
}

func NewUserNotificationHTTPClient(client *http.Client) UserNotificationHTTPClient {
	return &UserNotificationHTTPClientImpl{client}
}

// BatchUserNotifications BatchUserNotifications 批量操作
func (c *UserNotificationHTTPClientImpl) BatchUserNotifications(ctx context.Context, in *BatchUserNotificationsRequest, opts ...http.CallOption) (*BatchUserNotificationsReply, error) {
	var out BatchUserNotificationsReply
	pattern := "/api/v1/user/notification/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserNotificationBatchUserNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteUserNotification DeleteUserNotification 删除用户消息
func (c *UserNotificationHTTPClientImpl) DeleteUserNotification(ctx context.Context, in *DeleteUserNotificationRequest, opts ...http.CallOption) (*DeleteUserNotificationReply, error) {
	var out DeleteUserNotificationReply
	pattern := "/api/v1/user/notification/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserNotificationDeleteUserNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserNotificationList GetUserNotificationList 查询用户消息列表
func (c *UserNotificationHTTPClientImpl) GetUserNotificationList(ctx context.Context, in *GetUserNotificationListRequest, opts ...http.CallOption) (*GetUserNotificationListReply, error) {
	var out GetUserNotificationListReply
	pattern := "/api/v1/user/notification/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserNotificationGetUserNotificationList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserAllNotificationStatus UpdateUserAllNotificationStatus 更新所有消息已读
func (c *UserNotificationHTTPClientImpl) UpdateUserAllNotificationStatus(ctx context.Context, in *UpdateUserAllNotificationStatusRequest, opts ...http.CallOption) (*UpdateUserAllNotificationStatusReply, error) {
	var out UpdateUserAllNotificationStatusReply
	pattern := "/api/v1/user/notification"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserNotificationUpdateUserAllNotificationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserNotificationStatus UpdateUserNotificationStatus 更新用户消息状态
func (c *UserNotificationHTTPClientImpl) UpdateUserNotificationStatus(ctx context.Context, in *UpdateUserNotificationStatusRequest, opts ...http.CallOption) (*UpdateUserNotificationStatusReply, error) {
	var out UpdateUserNotificationStatusReply
	pattern := "/api/v1/user/notification/status/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserNotificationUpdateUserNotificationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
