// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: user/notification/v1/notification.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserNotification_GetUserNotificationList_FullMethodName         = "/api.user.notification.v1.UserNotification/GetUserNotificationList"
	UserNotification_DeleteUserNotification_FullMethodName          = "/api.user.notification.v1.UserNotification/DeleteUserNotification"
	UserNotification_UpdateUserNotificationStatus_FullMethodName    = "/api.user.notification.v1.UserNotification/UpdateUserNotificationStatus"
	UserNotification_BatchUserNotifications_FullMethodName          = "/api.user.notification.v1.UserNotification/BatchUserNotifications"
	UserNotification_UpdateUserAllNotificationStatus_FullMethodName = "/api.user.notification.v1.UserNotification/UpdateUserAllNotificationStatus"
)

// UserNotificationClient is the client API for UserNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserNotificationClient interface {
	// GetUserNotificationList 查询用户消息列表
	GetUserNotificationList(ctx context.Context, in *GetUserNotificationListRequest, opts ...grpc.CallOption) (*GetUserNotificationListReply, error)
	// DeleteUserNotification 删除用户消息
	DeleteUserNotification(ctx context.Context, in *DeleteUserNotificationRequest, opts ...grpc.CallOption) (*DeleteUserNotificationReply, error)
	// UpdateUserNotificationStatus 更新用户消息状态
	UpdateUserNotificationStatus(ctx context.Context, in *UpdateUserNotificationStatusRequest, opts ...grpc.CallOption) (*UpdateUserNotificationStatusReply, error)
	// BatchUserNotifications 批量操作
	BatchUserNotifications(ctx context.Context, in *BatchUserNotificationsRequest, opts ...grpc.CallOption) (*BatchUserNotificationsReply, error)
	// UpdateUserAllNotificationStatus 更新所有消息已读
	UpdateUserAllNotificationStatus(ctx context.Context, in *UpdateUserAllNotificationStatusRequest, opts ...grpc.CallOption) (*UpdateUserAllNotificationStatusReply, error)
}

type userNotificationClient struct {
	cc grpc.ClientConnInterface
}

func NewUserNotificationClient(cc grpc.ClientConnInterface) UserNotificationClient {
	return &userNotificationClient{cc}
}

func (c *userNotificationClient) GetUserNotificationList(ctx context.Context, in *GetUserNotificationListRequest, opts ...grpc.CallOption) (*GetUserNotificationListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotificationListReply)
	err := c.cc.Invoke(ctx, UserNotification_GetUserNotificationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userNotificationClient) DeleteUserNotification(ctx context.Context, in *DeleteUserNotificationRequest, opts ...grpc.CallOption) (*DeleteUserNotificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserNotificationReply)
	err := c.cc.Invoke(ctx, UserNotification_DeleteUserNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userNotificationClient) UpdateUserNotificationStatus(ctx context.Context, in *UpdateUserNotificationStatusRequest, opts ...grpc.CallOption) (*UpdateUserNotificationStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserNotificationStatusReply)
	err := c.cc.Invoke(ctx, UserNotification_UpdateUserNotificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userNotificationClient) BatchUserNotifications(ctx context.Context, in *BatchUserNotificationsRequest, opts ...grpc.CallOption) (*BatchUserNotificationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUserNotificationsReply)
	err := c.cc.Invoke(ctx, UserNotification_BatchUserNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userNotificationClient) UpdateUserAllNotificationStatus(ctx context.Context, in *UpdateUserAllNotificationStatusRequest, opts ...grpc.CallOption) (*UpdateUserAllNotificationStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserAllNotificationStatusReply)
	err := c.cc.Invoke(ctx, UserNotification_UpdateUserAllNotificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserNotificationServer is the server API for UserNotification service.
// All implementations must embed UnimplementedUserNotificationServer
// for forward compatibility.
type UserNotificationServer interface {
	// GetUserNotificationList 查询用户消息列表
	GetUserNotificationList(context.Context, *GetUserNotificationListRequest) (*GetUserNotificationListReply, error)
	// DeleteUserNotification 删除用户消息
	DeleteUserNotification(context.Context, *DeleteUserNotificationRequest) (*DeleteUserNotificationReply, error)
	// UpdateUserNotificationStatus 更新用户消息状态
	UpdateUserNotificationStatus(context.Context, *UpdateUserNotificationStatusRequest) (*UpdateUserNotificationStatusReply, error)
	// BatchUserNotifications 批量操作
	BatchUserNotifications(context.Context, *BatchUserNotificationsRequest) (*BatchUserNotificationsReply, error)
	// UpdateUserAllNotificationStatus 更新所有消息已读
	UpdateUserAllNotificationStatus(context.Context, *UpdateUserAllNotificationStatusRequest) (*UpdateUserAllNotificationStatusReply, error)
	mustEmbedUnimplementedUserNotificationServer()
}

// UnimplementedUserNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserNotificationServer struct{}

func (UnimplementedUserNotificationServer) GetUserNotificationList(context.Context, *GetUserNotificationListRequest) (*GetUserNotificationListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotificationList not implemented")
}
func (UnimplementedUserNotificationServer) DeleteUserNotification(context.Context, *DeleteUserNotificationRequest) (*DeleteUserNotificationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserNotification not implemented")
}
func (UnimplementedUserNotificationServer) UpdateUserNotificationStatus(context.Context, *UpdateUserNotificationStatusRequest) (*UpdateUserNotificationStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserNotificationStatus not implemented")
}
func (UnimplementedUserNotificationServer) BatchUserNotifications(context.Context, *BatchUserNotificationsRequest) (*BatchUserNotificationsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUserNotifications not implemented")
}
func (UnimplementedUserNotificationServer) UpdateUserAllNotificationStatus(context.Context, *UpdateUserAllNotificationStatusRequest) (*UpdateUserAllNotificationStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserAllNotificationStatus not implemented")
}
func (UnimplementedUserNotificationServer) mustEmbedUnimplementedUserNotificationServer() {}
func (UnimplementedUserNotificationServer) testEmbeddedByValue()                          {}

// UnsafeUserNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserNotificationServer will
// result in compilation errors.
type UnsafeUserNotificationServer interface {
	mustEmbedUnimplementedUserNotificationServer()
}

func RegisterUserNotificationServer(s grpc.ServiceRegistrar, srv UserNotificationServer) {
	// If the following call panics, it indicates UnimplementedUserNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserNotification_ServiceDesc, srv)
}

func _UserNotification_GetUserNotificationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServer).GetUserNotificationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotification_GetUserNotificationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServer).GetUserNotificationList(ctx, req.(*GetUserNotificationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserNotification_DeleteUserNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServer).DeleteUserNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotification_DeleteUserNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServer).DeleteUserNotification(ctx, req.(*DeleteUserNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserNotification_UpdateUserNotificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserNotificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServer).UpdateUserNotificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotification_UpdateUserNotificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServer).UpdateUserNotificationStatus(ctx, req.(*UpdateUserNotificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserNotification_BatchUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServer).BatchUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotification_BatchUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServer).BatchUserNotifications(ctx, req.(*BatchUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserNotification_UpdateUserAllNotificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAllNotificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServer).UpdateUserAllNotificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotification_UpdateUserAllNotificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServer).UpdateUserAllNotificationStatus(ctx, req.(*UpdateUserAllNotificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserNotification_ServiceDesc is the grpc.ServiceDesc for UserNotification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserNotification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.notification.v1.UserNotification",
	HandlerType: (*UserNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserNotificationList",
			Handler:    _UserNotification_GetUserNotificationList_Handler,
		},
		{
			MethodName: "DeleteUserNotification",
			Handler:    _UserNotification_DeleteUserNotification_Handler,
		},
		{
			MethodName: "UpdateUserNotificationStatus",
			Handler:    _UserNotification_UpdateUserNotificationStatus_Handler,
		},
		{
			MethodName: "BatchUserNotifications",
			Handler:    _UserNotification_BatchUserNotifications_Handler,
		},
		{
			MethodName: "UpdateUserAllNotificationStatus",
			Handler:    _UserNotification_UpdateUserAllNotificationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/notification/v1/notification.proto",
}
